[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "https://bass-inspired-rightly.ngrok-free.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login.html"
  to = "/dashboard/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard/dashboard.html"
  status = 200
  force = true
