services:
  backend:
    build: 
      context: ./backend/waterQuality
      dockerfile: Dockerfile
    container_name: waterquality-backend
    ports:
      - "127.0.0.1:8080:8080"
    env_file: .env
    environment:
      TZ: "Europe/Istanbul"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      MQTT_BROKER_URL: tcp://mosquitto:1883
        #volumes:
      # - ./backend/waterQuality/src:/app/src
      #- ./backend/waterQuality/pom.xml:/app/pom.xml
    depends_on:
      - postgres
      - mosquitto

  postgres:
    image: postgres:14
    container_name: waterquality-postgres
    env_file: .env
    environment:
      TZ: "Europe/Istanbul"
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${PG_SUPER_USER} 
      POSTGRES_PASSWORD: ${PG_SUPER_PW}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: waterquality-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  frontend:
      image: nginx:alpine
      container_name: waterquality-frontend
      ports:
        - "80:80"
      environment:
        TZ: "Europe/Istanbul"
      volumes:
        - ./frontend/public:/usr/share/nginx/html:ro
        - ./frontend/wq-proxy.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - backend
volumes:
  postgres-data:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
