version: '3.8'
services:
  backend:
    build: 
      context: ./backend/waterQuality
      dockerfile: Dockerfile
    container_name: waterquality-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/waterquality
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      MQTT_BROKER_URL: tcp://mosquitto:1883
    volumes:
      - ./backend/waterQuality/src:/app/src
      - ./backend/waterQuality/pom.xml:/app/pom.xml
    depends_on:
      - postgres
      - mosquitto


  postgres:
    image: postgres:14
    container_name: waterquality-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: waterquality
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./csv_output:/csv_output

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: waterquality-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"   # if you want to use WebSockets as well (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  frontend:
      image: nginx:alpine
      container_name: waterquality-frontend
      ports:
        - "80:80"
      volumes:
        - ./frontend/public/dashboard:/usr/share/nginx/html:ro
        - ./frontend/wq-proxy.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - backend
volumes:
  postgres-data:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
