server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:waterquality-postgres}:5432/${DB_NAME:waterquality}
    username: ${DB_USER} 
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

mqtt:
  broker-url: tcp://mosquitto:1883
  client-id: spring-mqtt-server
  topic: sensors/#

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
jwt:
    secret: ${JWT_SECRET}
